spring:
  config:
    import:
      - classpath:/mail.yml
      - classpath:/spring.yml
      - classpath:/redis.yml

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWw=
