spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xoals4340@gmail.com
    password: dlfjs!255
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
